SHORA-1835 and SHORA-2031 - Use TF on local and fix op cp.
shorelinesoftware/terraform-provider-shoreline pull request #138
Opened 2024-12-30 14:35 UTC by denischiparus

2025-01-08 08:19 UTC, sergiuiacob1 commented on examples/resources/report_template/resource.tf
> +  name = "my_report_1"
Was this formatted via a dedicated TF formatter? the `=` operators should be vertically aligned in that case

2025-01-08 08:19 UTC, sergiuiacob1 commented on provider/opts.go
> +	defer response.Body.Close()
noice

2025-01-08 08:19 UTC, sergiuiacob1 commented on provider/provider.go
> +			if key == "principal" && k == "idp_name" {
What does this do? Should we decouple the fixes?

2025-01-08 09:44 UTC, amalia101 commented on provider/provider_conf.go
> +			"fail_over":               { "type": "string",  "optional": true, "default": "safe"},
It's not that urgent but these changes should also be added in the `tf_conf` file from  the `shoreline` repo

2025-01-08 09:44 UTC, amalia101 approved these changes

2025-01-08 11:52 UTC, sergiuiacob1 commented on provider/provider.go
> +			if key == "principal" && k == "idp_name" {
I'm a bit confused, will the `return k == "idp_name"` not always return true since we're inside of `if key == "principal" && k == "idp_name"`?

2025-01-08 13:18 UTC, sergiuiacob1 commented
Is there a reason this PR comes from a fork? I see that you forked the repo on your `denischiparus` account, and opened a PR from that repo to this one.

2025-01-08 13:20 UTC, sergiuiacob1 requested changes

2025-01-08 13:20 UTC, sergiuiacob1 commented on provider/opts.go
> +	defer response.Body.Close()
If the above `err` is not null, this defer will not run and it may cause a hanging connection. The `defer` should be right after the request is made

2025-01-09 12:23 UTC, sergiuiacob1 commented on provider/opts.go
> +	defer response.Body.Close()
Coming back – I may understand this now. I suppose the body only needs to be closed if the error is not nil. Is that correct?

2025-01-13 14:36 UTC, denischiparus commented on examples/resources/report_template/resource.tf
> +  name = "my_report_1"
There were too many spaces anyway. I aligned them now.

2025-01-13 14:46 UTC, denischiparus commented on provider/provider.go
> +			if key == "principal" && k == "idp_name" {
the confusion comes from naming 2 variables the same (k) ... I will rename the second one.

2025-01-13 14:48 UTC, denischiparus commented on provider/provider.go
> +			if key == "principal" && k == "idp_name" {
This fix is needed until we add a get principal class function in shoreline backend.
Taking into account that we want it to work now and that the Shoreline fix can take a while until it goes to release, I added this fix.

2025-01-13 14:52 UTC, denischiparus commented on provider/provider_conf.go
> +			"fail_over":               { "type": "string",  "optional": true, "default": "safe"},
👍

2025-01-13 14:56 UTC, denischiparus commented on provider/opts.go
> +	defer response.Body.Close()
Yes. That's the reason.

2025-01-13 15:10 UTC, sergiuiacob1 approved these changes
L
G
T
M

2025-01-13 15:12 UTC, merged

2025-01-13 15:17 UTC, denischiparus commented on provider/provider_conf.go
> +			"fail_over":               { "type": "string",  "optional": true, "default": "safe"},
https://github.com/shorelinesoftware/shoreline/pull/14460